# server.yml
server.serviceId: com.networknt.router-1.0.0
server.httpsPort: 7443

# router.yml
router.maxRequestTime: 1000

# service.yml
service.singletons:
  - com.networknt.registry.URL:
      - com.networknt.registry.URLImpl:
          parameters:
            com.networknt.petstore-1.0.0: https://localhost:9443
  - com.networknt.registry.Registry:
      - com.networknt.registry.support.DirectRegistry
  - com.networknt.balance.LoadBalance:
      - com.networknt.balance.RoundRobinLoadBalance
  - com.networknt.cluster.Cluster:
      - com.networknt.cluster.LightCluster

# pathPrefixService.yml
pathPrefixService.enabled: true
pathPrefixService.mapping:
  /v1: com.networknt.petstore-1.0.0
